# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 13:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Olymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 3, 9, 16, 31, 5, 442883))),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemWithMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ManyToManyField(blank=True, default=None, to='olymp.Mark')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=200)),
                ('secondName', models.CharField(default='', max_length=200)),
                ('surName', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('olymp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Olymp')),
                ('problems', models.ManyToManyField(to='olymp.ProblemWithMark')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.University'),
        ),
        migrations.AddField(
            model_name='problem',
            name='prType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.ProblemType'),
        ),
        migrations.AddField(
            model_name='olymp',
            name='problems',
            field=models.ManyToManyField(blank=True, default=None, to='olymp.Problem'),
        ),
        migrations.AddField(
            model_name='expert',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.University'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
