# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0002_auto_20170309_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='olymp',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='olymp',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 9, 16, 44, 52, 500929)),
        ),
    ]
