# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0003_auto_20170309_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('prType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.ProblemType')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInOlymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('pInB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.ProblemInBank')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProblemWithMark',
            new_name='ProblemInOlympWithMark',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='prType',
        ),
        migrations.AlterField(
            model_name='olymp',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 9, 17, 34, 34, 119773)),
        ),
        migrations.AlterField(
            model_name='olymp',
            name='problems',
            field=models.ManyToManyField(blank=True, default=None, to='olymp.ProblemInOlymp'),
        ),
        migrations.AlterField(
            model_name='probleminolympwithmark',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.ProblemInOlymp'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
