# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0007_auto_20170310_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='ecspertType',
            field=models.ManyToManyField(blank=True, default=None, to='olymp.ProblemType'),
        ),
        migrations.AlterField(
            model_name='olymp',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 10, 5, 36, 9, 684457)),
        ),
    ]
