# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0008_auto_20170310_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AlterField(
            model_name='olymp',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
